version: "3.9"

services:

  postgres-db:
    image: postgres
    volumes:
      - ~/$USERNAME/temp/book-rating-db/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5435:5432"

  web-server:
    build: .
    container_name: web-server
    command: >
      sh -c "flake8 /code/book_rating_backend
      && python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8002"
    volumes:
      - .:/code
    ports:
      - "8002:8002"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres-db
